// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tsz.Api.Persistence;

#nullable disable

namespace Tsz.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523212259_AddHolidays")]
    partial class AddHolidays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Tsz.Modules.Contracts.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientManagerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Tsz.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientManagerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Tsz.Modules.Users.Domain.LeaveTypes.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultAllowed")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DefaultDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LeaveTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            DefaultAllowed = "Limited",
                            DefaultDays = 20m,
                            Name = "Verlof"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            DefaultAllowed = "Limited",
                            DefaultDays = 5m,
                            Name = "ADV dagen"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            DefaultAllowed = "Limited",
                            DefaultDays = 0m,
                            Name = "Anciënniteit"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            DefaultAllowed = "Unlimited",
                            Name = "Ziekte"
                        });
                });

            modelBuilder.Entity("Tsz.Modules.Users.Domain.Leaves.UserLeave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("UserLeaves", (string)null);
                });

            modelBuilder.Entity("Tsz.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraOid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("EntraOid")
                        .IsUnique()
                        .HasFilter("\"EntraOid\" IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Tsz.Modules.Workdays.Domain.Holidays.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Country", "Date")
                        .IsUnique();

                    b.ToTable("Holidays", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 1, 1),
                            Name = "New Year's Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000002-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 4, 6),
                            Name = "Easter Monday",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000003-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 5, 1),
                            Name = "Labour Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000004-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 5, 14),
                            Name = "Ascension Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000005-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 5, 25),
                            Name = "Whit Monday",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000006-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 7, 21),
                            Name = "Belgian National Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000007-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 8, 15),
                            Name = "Assumption of Mary",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000008-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 11, 1),
                            Name = "All Saints' Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000009-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 11, 11),
                            Name = "Armistice Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a1000010-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2026, 12, 25),
                            Name = "Christmas Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000001-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 1, 1),
                            Name = "New Year's Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000002-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 3, 29),
                            Name = "Easter Monday",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000003-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 5, 1),
                            Name = "Labour Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000004-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 5, 6),
                            Name = "Ascension Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000005-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 5, 17),
                            Name = "Whit Monday",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000006-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 7, 21),
                            Name = "Belgian National Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000007-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 8, 15),
                            Name = "Assumption of Mary",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000008-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 11, 1),
                            Name = "All Saints' Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000009-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 11, 11),
                            Name = "Armistice Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2000010-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2027, 12, 25),
                            Name = "Christmas Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000001-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 1, 1),
                            Name = "New Year's Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000002-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 4, 17),
                            Name = "Easter Monday",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000003-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 5, 1),
                            Name = "Labour Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000004-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 5, 25),
                            Name = "Ascension Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000005-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 6, 5),
                            Name = "Whit Monday",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000006-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 7, 21),
                            Name = "Belgian National Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000007-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 8, 15),
                            Name = "Assumption of Mary",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000008-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 11, 1),
                            Name = "All Saints' Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000009-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 11, 11),
                            Name = "Armistice Day",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a3000010-0000-0000-0000-000000000000"),
                            Country = "BE",
                            Date = new DateOnly(2028, 12, 25),
                            Name = "Christmas Day",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Tsz.Modules.Contracts.Domain.Contracts.Contract", b =>
                {
                    b.OwnsMany("Tsz.Modules.Contracts.Domain.Contracts.ContractConsultant", "Consultants", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContractId", "UserId");

                            b1.ToTable("ContractConsultants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.OwnsMany("Tsz.Modules.Contracts.Domain.Contracts.ContractTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ContractId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Rate")
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ContractId");

                            b1.ToTable("ContractTasks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractId");
                        });

                    b.Navigation("Consultants");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Tsz.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("Tsz.Modules.Customers.Domain.Customers.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .HasMaxLength(128)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("Zip")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address_Zip");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("Tsz.Modules.Customers.Domain.Customers.ContactPerson", "ContactPerson", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactPerson_Email");

                            b1.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContactPerson_Name");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactPerson")
                        .IsRequired();
                });

            modelBuilder.Entity("Tsz.Modules.Users.Domain.Leaves.UserLeave", b =>
                {
                    b.HasOne("Tsz.Modules.Users.Domain.LeaveTypes.LeaveType", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tsz.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tsz.Modules.Users.Domain.Users.User", b =>
                {
                    b.OwnsMany("Tsz.Modules.Users.Domain.Users.UserRoleAssignment", "RoleAssignments", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Role")
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");

                            b1.HasKey("UserId", "Role");

                            b1.ToTable("UserRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
