/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAdminUsersIndexRouteImport } from './routes/_protected/admin/users/index'
import { Route as ProtectedAdminCustomersIndexRouteImport } from './routes/_protected/admin/customers/index'
import { Route as ProtectedAdminContractsIndexRouteImport } from './routes/_protected/admin/contracts/index'
import { Route as ProtectedAdminUsersNewRouteImport } from './routes/_protected/admin/users/new'
import { Route as ProtectedAdminUsersIdRouteImport } from './routes/_protected/admin/users/$id'
import { Route as ProtectedAdminCustomersNewRouteImport } from './routes/_protected/admin/customers/new'
import { Route as ProtectedAdminCustomersIdRouteImport } from './routes/_protected/admin/customers/$id'
import { Route as ProtectedAdminContractsNewRouteImport } from './routes/_protected/admin/contracts/new'
import { Route as ProtectedAdminContractsContractIdRouteImport } from './routes/_protected/admin/contracts/$contractId'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminUsersIndexRoute =
  ProtectedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminCustomersIndexRoute =
  ProtectedAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminContractsIndexRoute =
  ProtectedAdminContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminUsersNewRoute = ProtectedAdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminUsersIdRoute = ProtectedAdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminCustomersNewRoute =
  ProtectedAdminCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminCustomersIdRoute =
  ProtectedAdminCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminContractsNewRoute =
  ProtectedAdminContractsNewRouteImport.update({
    id: '/contracts/new',
    path: '/contracts/new',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminContractsContractIdRoute =
  ProtectedAdminContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/contracts/$contractId': typeof ProtectedAdminContractsContractIdRoute
  '/admin/contracts/new': typeof ProtectedAdminContractsNewRoute
  '/admin/customers/$id': typeof ProtectedAdminCustomersIdRoute
  '/admin/customers/new': typeof ProtectedAdminCustomersNewRoute
  '/admin/users/$id': typeof ProtectedAdminUsersIdRoute
  '/admin/users/new': typeof ProtectedAdminUsersNewRoute
  '/admin/contracts/': typeof ProtectedAdminContractsIndexRoute
  '/admin/customers/': typeof ProtectedAdminCustomersIndexRoute
  '/admin/users/': typeof ProtectedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/no-access': typeof NoAccessRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/contracts/$contractId': typeof ProtectedAdminContractsContractIdRoute
  '/admin/contracts/new': typeof ProtectedAdminContractsNewRoute
  '/admin/customers/$id': typeof ProtectedAdminCustomersIdRoute
  '/admin/customers/new': typeof ProtectedAdminCustomersNewRoute
  '/admin/users/$id': typeof ProtectedAdminUsersIdRoute
  '/admin/users/new': typeof ProtectedAdminUsersNewRoute
  '/admin/contracts': typeof ProtectedAdminContractsIndexRoute
  '/admin/customers': typeof ProtectedAdminCustomersIndexRoute
  '/admin/users': typeof ProtectedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/admin/contracts/$contractId': typeof ProtectedAdminContractsContractIdRoute
  '/_protected/admin/contracts/new': typeof ProtectedAdminContractsNewRoute
  '/_protected/admin/customers/$id': typeof ProtectedAdminCustomersIdRoute
  '/_protected/admin/customers/new': typeof ProtectedAdminCustomersNewRoute
  '/_protected/admin/users/$id': typeof ProtectedAdminUsersIdRoute
  '/_protected/admin/users/new': typeof ProtectedAdminUsersNewRoute
  '/_protected/admin/contracts/': typeof ProtectedAdminContractsIndexRoute
  '/_protected/admin/customers/': typeof ProtectedAdminCustomersIndexRoute
  '/_protected/admin/users/': typeof ProtectedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/no-access'
    | '/admin'
    | '/api/auth/$'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/contracts/'
    | '/admin/customers/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/no-access'
    | '/admin'
    | '/'
    | '/api/auth/$'
    | '/admin/contracts/$contractId'
    | '/admin/contracts/new'
    | '/admin/customers/$id'
    | '/admin/customers/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/contracts'
    | '/admin/customers'
    | '/admin/users'
  id:
    | '__root__'
    | '/_protected'
    | '/no-access'
    | '/_protected/admin'
    | '/_protected/'
    | '/api/auth/$'
    | '/_protected/admin/contracts/$contractId'
    | '/_protected/admin/contracts/new'
    | '/_protected/admin/customers/$id'
    | '/_protected/admin/customers/new'
    | '/_protected/admin/users/$id'
    | '/_protected/admin/users/new'
    | '/_protected/admin/contracts/'
    | '/_protected/admin/customers/'
    | '/_protected/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  NoAccessRoute: typeof NoAccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/users/': {
      id: '/_protected/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof ProtectedAdminUsersIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/customers/': {
      id: '/_protected/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof ProtectedAdminCustomersIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/contracts/': {
      id: '/_protected/admin/contracts/'
      path: '/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof ProtectedAdminContractsIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/users/new': {
      id: '/_protected/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof ProtectedAdminUsersNewRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/users/$id': {
      id: '/_protected/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof ProtectedAdminUsersIdRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/customers/new': {
      id: '/_protected/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof ProtectedAdminCustomersNewRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/customers/$id': {
      id: '/_protected/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof ProtectedAdminCustomersIdRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/contracts/new': {
      id: '/_protected/admin/contracts/new'
      path: '/contracts/new'
      fullPath: '/admin/contracts/new'
      preLoaderRoute: typeof ProtectedAdminContractsNewRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/contracts/$contractId': {
      id: '/_protected/admin/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/admin/contracts/$contractId'
      preLoaderRoute: typeof ProtectedAdminContractsContractIdRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface ProtectedAdminRouteChildren {
  ProtectedAdminContractsContractIdRoute: typeof ProtectedAdminContractsContractIdRoute
  ProtectedAdminContractsNewRoute: typeof ProtectedAdminContractsNewRoute
  ProtectedAdminCustomersIdRoute: typeof ProtectedAdminCustomersIdRoute
  ProtectedAdminCustomersNewRoute: typeof ProtectedAdminCustomersNewRoute
  ProtectedAdminUsersIdRoute: typeof ProtectedAdminUsersIdRoute
  ProtectedAdminUsersNewRoute: typeof ProtectedAdminUsersNewRoute
  ProtectedAdminContractsIndexRoute: typeof ProtectedAdminContractsIndexRoute
  ProtectedAdminCustomersIndexRoute: typeof ProtectedAdminCustomersIndexRoute
  ProtectedAdminUsersIndexRoute: typeof ProtectedAdminUsersIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminContractsContractIdRoute:
    ProtectedAdminContractsContractIdRoute,
  ProtectedAdminContractsNewRoute: ProtectedAdminContractsNewRoute,
  ProtectedAdminCustomersIdRoute: ProtectedAdminCustomersIdRoute,
  ProtectedAdminCustomersNewRoute: ProtectedAdminCustomersNewRoute,
  ProtectedAdminUsersIdRoute: ProtectedAdminUsersIdRoute,
  ProtectedAdminUsersNewRoute: ProtectedAdminUsersNewRoute,
  ProtectedAdminContractsIndexRoute: ProtectedAdminContractsIndexRoute,
  ProtectedAdminCustomersIndexRoute: ProtectedAdminCustomersIndexRoute,
  ProtectedAdminUsersIndexRoute: ProtectedAdminUsersIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  NoAccessRoute: NoAccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
