/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAuthenticatedRouteImport } from './routes/_protected/_authenticated'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAuthenticatedTimesheetsRouteImport } from './routes/_protected/_authenticated/timesheets'
import { Route as ProtectedAuthenticatedTimeEntryRouteImport } from './routes/_protected/_authenticated/time-entry'
import { Route as ProtectedAuthenticatedCustomersRouteImport } from './routes/_protected/_authenticated/customers'
import { Route as ProtectedAuthenticatedContractsRouteImport } from './routes/_protected/_authenticated/contracts'
import { Route as ProtectedAuthenticatedAdminRouteImport } from './routes/_protected/_authenticated/admin'
import { Route as ProtectedAuthenticatedTimesheetsIndexRouteImport } from './routes/_protected/_authenticated/timesheets/index'
import { Route as ProtectedAuthenticatedTimeEntryIndexRouteImport } from './routes/_protected/_authenticated/time-entry/index'
import { Route as ProtectedAuthenticatedLeavesIndexRouteImport } from './routes/_protected/_authenticated/leaves/index'
import { Route as ProtectedAuthenticatedCustomersIndexRouteImport } from './routes/_protected/_authenticated/customers/index'
import { Route as ProtectedAuthenticatedContractsIndexRouteImport } from './routes/_protected/_authenticated/contracts/index'
import { Route as ProtectedAuthenticatedLeavesYearRouteImport } from './routes/_protected/_authenticated/leaves/$year'
import { Route as ProtectedAuthenticatedCustomersNewRouteImport } from './routes/_protected/_authenticated/customers/new'
import { Route as ProtectedAuthenticatedCustomersIdRouteImport } from './routes/_protected/_authenticated/customers/$id'
import { Route as ProtectedAuthenticatedContractsNewRouteImport } from './routes/_protected/_authenticated/contracts/new'
import { Route as ProtectedAuthenticatedContractsContractIdRouteImport } from './routes/_protected/_authenticated/contracts/$contractId'
import { Route as ProtectedAuthenticatedAdminUsersRouteImport } from './routes/_protected/_authenticated/admin/users'
import { Route as ProtectedAuthenticatedTimeEntryWeekIndexRouteImport } from './routes/_protected/_authenticated/time-entry/week/index'
import { Route as ProtectedAuthenticatedTimeEntryMonthIndexRouteImport } from './routes/_protected/_authenticated/time-entry/month/index'
import { Route as ProtectedAuthenticatedAdminUsersIndexRouteImport } from './routes/_protected/_authenticated/admin/users/index'
import { Route as ProtectedAuthenticatedAdminUsersNewRouteImport } from './routes/_protected/_authenticated/admin/users/new'
import { Route as ProtectedAuthenticatedAdminUsersIdRouteImport } from './routes/_protected/_authenticated/admin/users/$id'
import { Route as ProtectedAuthenticatedTimesheetsPrintYearMonthRouteImport } from './routes/_protected/_authenticated/timesheets/print/$year/$month'
import { Route as ProtectedAuthenticatedTimeEntryWeekYearWeekRouteImport } from './routes/_protected/_authenticated/time-entry/week/$year/$week'
import { Route as ProtectedAuthenticatedTimeEntryMonthYearMonthRouteImport } from './routes/_protected/_authenticated/time-entry/month/$year/$month'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuthenticatedRoute = ProtectedAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAuthenticatedTimesheetsRoute =
  ProtectedAuthenticatedTimesheetsRouteImport.update({
    id: '/timesheets',
    path: '/timesheets',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedTimeEntryRoute =
  ProtectedAuthenticatedTimeEntryRouteImport.update({
    id: '/time-entry',
    path: '/time-entry',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedCustomersRoute =
  ProtectedAuthenticatedCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedContractsRoute =
  ProtectedAuthenticatedContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedAdminRoute =
  ProtectedAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedTimesheetsIndexRoute =
  ProtectedAuthenticatedTimesheetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAuthenticatedTimesheetsRoute,
  } as any)
const ProtectedAuthenticatedTimeEntryIndexRoute =
  ProtectedAuthenticatedTimeEntryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAuthenticatedTimeEntryRoute,
  } as any)
const ProtectedAuthenticatedLeavesIndexRoute =
  ProtectedAuthenticatedLeavesIndexRouteImport.update({
    id: '/leaves/',
    path: '/leaves/',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedCustomersIndexRoute =
  ProtectedAuthenticatedCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAuthenticatedCustomersRoute,
  } as any)
const ProtectedAuthenticatedContractsIndexRoute =
  ProtectedAuthenticatedContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAuthenticatedContractsRoute,
  } as any)
const ProtectedAuthenticatedLeavesYearRoute =
  ProtectedAuthenticatedLeavesYearRouteImport.update({
    id: '/leaves/$year',
    path: '/leaves/$year',
    getParentRoute: () => ProtectedAuthenticatedRoute,
  } as any)
const ProtectedAuthenticatedCustomersNewRoute =
  ProtectedAuthenticatedCustomersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedAuthenticatedCustomersRoute,
  } as any)
const ProtectedAuthenticatedCustomersIdRoute =
  ProtectedAuthenticatedCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedAuthenticatedCustomersRoute,
  } as any)
const ProtectedAuthenticatedContractsNewRoute =
  ProtectedAuthenticatedContractsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedAuthenticatedContractsRoute,
  } as any)
const ProtectedAuthenticatedContractsContractIdRoute =
  ProtectedAuthenticatedContractsContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => ProtectedAuthenticatedContractsRoute,
  } as any)
const ProtectedAuthenticatedAdminUsersRoute =
  ProtectedAuthenticatedAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedAuthenticatedAdminRoute,
  } as any)
const ProtectedAuthenticatedTimeEntryWeekIndexRoute =
  ProtectedAuthenticatedTimeEntryWeekIndexRouteImport.update({
    id: '/week/',
    path: '/week/',
    getParentRoute: () => ProtectedAuthenticatedTimeEntryRoute,
  } as any)
const ProtectedAuthenticatedTimeEntryMonthIndexRoute =
  ProtectedAuthenticatedTimeEntryMonthIndexRouteImport.update({
    id: '/month/',
    path: '/month/',
    getParentRoute: () => ProtectedAuthenticatedTimeEntryRoute,
  } as any)
const ProtectedAuthenticatedAdminUsersIndexRoute =
  ProtectedAuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAuthenticatedAdminUsersRoute,
  } as any)
const ProtectedAuthenticatedAdminUsersNewRoute =
  ProtectedAuthenticatedAdminUsersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedAuthenticatedAdminUsersRoute,
  } as any)
const ProtectedAuthenticatedAdminUsersIdRoute =
  ProtectedAuthenticatedAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedAuthenticatedAdminUsersRoute,
  } as any)
const ProtectedAuthenticatedTimesheetsPrintYearMonthRoute =
  ProtectedAuthenticatedTimesheetsPrintYearMonthRouteImport.update({
    id: '/print/$year/$month',
    path: '/print/$year/$month',
    getParentRoute: () => ProtectedAuthenticatedTimesheetsRoute,
  } as any)
const ProtectedAuthenticatedTimeEntryWeekYearWeekRoute =
  ProtectedAuthenticatedTimeEntryWeekYearWeekRouteImport.update({
    id: '/week/$year/$week',
    path: '/week/$year/$week',
    getParentRoute: () => ProtectedAuthenticatedTimeEntryRoute,
  } as any)
const ProtectedAuthenticatedTimeEntryMonthYearMonthRoute =
  ProtectedAuthenticatedTimeEntryMonthYearMonthRouteImport.update({
    id: '/month/$year/$month',
    path: '/month/$year/$month',
    getParentRoute: () => ProtectedAuthenticatedTimeEntryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/no-access': typeof NoAccessRoute
  '/admin': typeof ProtectedAuthenticatedAdminRouteWithChildren
  '/contracts': typeof ProtectedAuthenticatedContractsRouteWithChildren
  '/customers': typeof ProtectedAuthenticatedCustomersRouteWithChildren
  '/time-entry': typeof ProtectedAuthenticatedTimeEntryRouteWithChildren
  '/timesheets': typeof ProtectedAuthenticatedTimesheetsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/users': typeof ProtectedAuthenticatedAdminUsersRouteWithChildren
  '/contracts/$contractId': typeof ProtectedAuthenticatedContractsContractIdRoute
  '/contracts/new': typeof ProtectedAuthenticatedContractsNewRoute
  '/customers/$id': typeof ProtectedAuthenticatedCustomersIdRoute
  '/customers/new': typeof ProtectedAuthenticatedCustomersNewRoute
  '/leaves/$year': typeof ProtectedAuthenticatedLeavesYearRoute
  '/contracts/': typeof ProtectedAuthenticatedContractsIndexRoute
  '/customers/': typeof ProtectedAuthenticatedCustomersIndexRoute
  '/leaves/': typeof ProtectedAuthenticatedLeavesIndexRoute
  '/time-entry/': typeof ProtectedAuthenticatedTimeEntryIndexRoute
  '/timesheets/': typeof ProtectedAuthenticatedTimesheetsIndexRoute
  '/admin/users/$id': typeof ProtectedAuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof ProtectedAuthenticatedAdminUsersNewRoute
  '/admin/users/': typeof ProtectedAuthenticatedAdminUsersIndexRoute
  '/time-entry/month/': typeof ProtectedAuthenticatedTimeEntryMonthIndexRoute
  '/time-entry/week/': typeof ProtectedAuthenticatedTimeEntryWeekIndexRoute
  '/time-entry/month/$year/$month': typeof ProtectedAuthenticatedTimeEntryMonthYearMonthRoute
  '/time-entry/week/$year/$week': typeof ProtectedAuthenticatedTimeEntryWeekYearWeekRoute
  '/timesheets/print/$year/$month': typeof ProtectedAuthenticatedTimesheetsPrintYearMonthRoute
}
export interface FileRoutesByTo {
  '/no-access': typeof NoAccessRoute
  '/': typeof ProtectedIndexRoute
  '/admin': typeof ProtectedAuthenticatedAdminRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contracts/$contractId': typeof ProtectedAuthenticatedContractsContractIdRoute
  '/contracts/new': typeof ProtectedAuthenticatedContractsNewRoute
  '/customers/$id': typeof ProtectedAuthenticatedCustomersIdRoute
  '/customers/new': typeof ProtectedAuthenticatedCustomersNewRoute
  '/leaves/$year': typeof ProtectedAuthenticatedLeavesYearRoute
  '/contracts': typeof ProtectedAuthenticatedContractsIndexRoute
  '/customers': typeof ProtectedAuthenticatedCustomersIndexRoute
  '/leaves': typeof ProtectedAuthenticatedLeavesIndexRoute
  '/time-entry': typeof ProtectedAuthenticatedTimeEntryIndexRoute
  '/timesheets': typeof ProtectedAuthenticatedTimesheetsIndexRoute
  '/admin/users/$id': typeof ProtectedAuthenticatedAdminUsersIdRoute
  '/admin/users/new': typeof ProtectedAuthenticatedAdminUsersNewRoute
  '/admin/users': typeof ProtectedAuthenticatedAdminUsersIndexRoute
  '/time-entry/month': typeof ProtectedAuthenticatedTimeEntryMonthIndexRoute
  '/time-entry/week': typeof ProtectedAuthenticatedTimeEntryWeekIndexRoute
  '/time-entry/month/$year/$month': typeof ProtectedAuthenticatedTimeEntryMonthYearMonthRoute
  '/time-entry/week/$year/$week': typeof ProtectedAuthenticatedTimeEntryWeekYearWeekRoute
  '/timesheets/print/$year/$month': typeof ProtectedAuthenticatedTimesheetsPrintYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/no-access': typeof NoAccessRoute
  '/_protected/_authenticated': typeof ProtectedAuthenticatedRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/_authenticated/admin': typeof ProtectedAuthenticatedAdminRouteWithChildren
  '/_protected/_authenticated/contracts': typeof ProtectedAuthenticatedContractsRouteWithChildren
  '/_protected/_authenticated/customers': typeof ProtectedAuthenticatedCustomersRouteWithChildren
  '/_protected/_authenticated/time-entry': typeof ProtectedAuthenticatedTimeEntryRouteWithChildren
  '/_protected/_authenticated/timesheets': typeof ProtectedAuthenticatedTimesheetsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/_authenticated/admin/users': typeof ProtectedAuthenticatedAdminUsersRouteWithChildren
  '/_protected/_authenticated/contracts/$contractId': typeof ProtectedAuthenticatedContractsContractIdRoute
  '/_protected/_authenticated/contracts/new': typeof ProtectedAuthenticatedContractsNewRoute
  '/_protected/_authenticated/customers/$id': typeof ProtectedAuthenticatedCustomersIdRoute
  '/_protected/_authenticated/customers/new': typeof ProtectedAuthenticatedCustomersNewRoute
  '/_protected/_authenticated/leaves/$year': typeof ProtectedAuthenticatedLeavesYearRoute
  '/_protected/_authenticated/contracts/': typeof ProtectedAuthenticatedContractsIndexRoute
  '/_protected/_authenticated/customers/': typeof ProtectedAuthenticatedCustomersIndexRoute
  '/_protected/_authenticated/leaves/': typeof ProtectedAuthenticatedLeavesIndexRoute
  '/_protected/_authenticated/time-entry/': typeof ProtectedAuthenticatedTimeEntryIndexRoute
  '/_protected/_authenticated/timesheets/': typeof ProtectedAuthenticatedTimesheetsIndexRoute
  '/_protected/_authenticated/admin/users/$id': typeof ProtectedAuthenticatedAdminUsersIdRoute
  '/_protected/_authenticated/admin/users/new': typeof ProtectedAuthenticatedAdminUsersNewRoute
  '/_protected/_authenticated/admin/users/': typeof ProtectedAuthenticatedAdminUsersIndexRoute
  '/_protected/_authenticated/time-entry/month/': typeof ProtectedAuthenticatedTimeEntryMonthIndexRoute
  '/_protected/_authenticated/time-entry/week/': typeof ProtectedAuthenticatedTimeEntryWeekIndexRoute
  '/_protected/_authenticated/time-entry/month/$year/$month': typeof ProtectedAuthenticatedTimeEntryMonthYearMonthRoute
  '/_protected/_authenticated/time-entry/week/$year/$week': typeof ProtectedAuthenticatedTimeEntryWeekYearWeekRoute
  '/_protected/_authenticated/timesheets/print/$year/$month': typeof ProtectedAuthenticatedTimesheetsPrintYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/no-access'
    | '/admin'
    | '/contracts'
    | '/customers'
    | '/time-entry'
    | '/timesheets'
    | '/api/auth/$'
    | '/admin/users'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/leaves/$year'
    | '/contracts/'
    | '/customers/'
    | '/leaves/'
    | '/time-entry/'
    | '/timesheets/'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/users/'
    | '/time-entry/month/'
    | '/time-entry/week/'
    | '/time-entry/month/$year/$month'
    | '/time-entry/week/$year/$week'
    | '/timesheets/print/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/no-access'
    | '/'
    | '/admin'
    | '/api/auth/$'
    | '/contracts/$contractId'
    | '/contracts/new'
    | '/customers/$id'
    | '/customers/new'
    | '/leaves/$year'
    | '/contracts'
    | '/customers'
    | '/leaves'
    | '/time-entry'
    | '/timesheets'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/users'
    | '/time-entry/month'
    | '/time-entry/week'
    | '/time-entry/month/$year/$month'
    | '/time-entry/week/$year/$week'
    | '/timesheets/print/$year/$month'
  id:
    | '__root__'
    | '/_protected'
    | '/no-access'
    | '/_protected/_authenticated'
    | '/_protected/'
    | '/_protected/_authenticated/admin'
    | '/_protected/_authenticated/contracts'
    | '/_protected/_authenticated/customers'
    | '/_protected/_authenticated/time-entry'
    | '/_protected/_authenticated/timesheets'
    | '/api/auth/$'
    | '/_protected/_authenticated/admin/users'
    | '/_protected/_authenticated/contracts/$contractId'
    | '/_protected/_authenticated/contracts/new'
    | '/_protected/_authenticated/customers/$id'
    | '/_protected/_authenticated/customers/new'
    | '/_protected/_authenticated/leaves/$year'
    | '/_protected/_authenticated/contracts/'
    | '/_protected/_authenticated/customers/'
    | '/_protected/_authenticated/leaves/'
    | '/_protected/_authenticated/time-entry/'
    | '/_protected/_authenticated/timesheets/'
    | '/_protected/_authenticated/admin/users/$id'
    | '/_protected/_authenticated/admin/users/new'
    | '/_protected/_authenticated/admin/users/'
    | '/_protected/_authenticated/time-entry/month/'
    | '/_protected/_authenticated/time-entry/week/'
    | '/_protected/_authenticated/time-entry/month/$year/$month'
    | '/_protected/_authenticated/time-entry/week/$year/$week'
    | '/_protected/_authenticated/timesheets/print/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  NoAccessRoute: typeof NoAccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_authenticated': {
      id: '/_protected/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAuthenticatedRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_authenticated/timesheets': {
      id: '/_protected/_authenticated/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof ProtectedAuthenticatedTimesheetsRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/time-entry': {
      id: '/_protected/_authenticated/time-entry'
      path: '/time-entry'
      fullPath: '/time-entry'
      preLoaderRoute: typeof ProtectedAuthenticatedTimeEntryRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/customers': {
      id: '/_protected/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedAuthenticatedCustomersRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/contracts': {
      id: '/_protected/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ProtectedAuthenticatedContractsRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/admin': {
      id: '/_protected/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAuthenticatedAdminRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/timesheets/': {
      id: '/_protected/_authenticated/timesheets/'
      path: '/'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof ProtectedAuthenticatedTimesheetsIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimesheetsRoute
    }
    '/_protected/_authenticated/time-entry/': {
      id: '/_protected/_authenticated/time-entry/'
      path: '/'
      fullPath: '/time-entry/'
      preLoaderRoute: typeof ProtectedAuthenticatedTimeEntryIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimeEntryRoute
    }
    '/_protected/_authenticated/leaves/': {
      id: '/_protected/_authenticated/leaves/'
      path: '/leaves'
      fullPath: '/leaves/'
      preLoaderRoute: typeof ProtectedAuthenticatedLeavesIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/customers/': {
      id: '/_protected/_authenticated/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof ProtectedAuthenticatedCustomersIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedCustomersRoute
    }
    '/_protected/_authenticated/contracts/': {
      id: '/_protected/_authenticated/contracts/'
      path: '/'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ProtectedAuthenticatedContractsIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedContractsRoute
    }
    '/_protected/_authenticated/leaves/$year': {
      id: '/_protected/_authenticated/leaves/$year'
      path: '/leaves/$year'
      fullPath: '/leaves/$year'
      preLoaderRoute: typeof ProtectedAuthenticatedLeavesYearRouteImport
      parentRoute: typeof ProtectedAuthenticatedRoute
    }
    '/_protected/_authenticated/customers/new': {
      id: '/_protected/_authenticated/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof ProtectedAuthenticatedCustomersNewRouteImport
      parentRoute: typeof ProtectedAuthenticatedCustomersRoute
    }
    '/_protected/_authenticated/customers/$id': {
      id: '/_protected/_authenticated/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof ProtectedAuthenticatedCustomersIdRouteImport
      parentRoute: typeof ProtectedAuthenticatedCustomersRoute
    }
    '/_protected/_authenticated/contracts/new': {
      id: '/_protected/_authenticated/contracts/new'
      path: '/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ProtectedAuthenticatedContractsNewRouteImport
      parentRoute: typeof ProtectedAuthenticatedContractsRoute
    }
    '/_protected/_authenticated/contracts/$contractId': {
      id: '/_protected/_authenticated/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ProtectedAuthenticatedContractsContractIdRouteImport
      parentRoute: typeof ProtectedAuthenticatedContractsRoute
    }
    '/_protected/_authenticated/admin/users': {
      id: '/_protected/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAuthenticatedAdminUsersRouteImport
      parentRoute: typeof ProtectedAuthenticatedAdminRoute
    }
    '/_protected/_authenticated/time-entry/week/': {
      id: '/_protected/_authenticated/time-entry/week/'
      path: '/week'
      fullPath: '/time-entry/week/'
      preLoaderRoute: typeof ProtectedAuthenticatedTimeEntryWeekIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimeEntryRoute
    }
    '/_protected/_authenticated/time-entry/month/': {
      id: '/_protected/_authenticated/time-entry/month/'
      path: '/month'
      fullPath: '/time-entry/month/'
      preLoaderRoute: typeof ProtectedAuthenticatedTimeEntryMonthIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimeEntryRoute
    }
    '/_protected/_authenticated/admin/users/': {
      id: '/_protected/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof ProtectedAuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof ProtectedAuthenticatedAdminUsersRoute
    }
    '/_protected/_authenticated/admin/users/new': {
      id: '/_protected/_authenticated/admin/users/new'
      path: '/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof ProtectedAuthenticatedAdminUsersNewRouteImport
      parentRoute: typeof ProtectedAuthenticatedAdminUsersRoute
    }
    '/_protected/_authenticated/admin/users/$id': {
      id: '/_protected/_authenticated/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof ProtectedAuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof ProtectedAuthenticatedAdminUsersRoute
    }
    '/_protected/_authenticated/timesheets/print/$year/$month': {
      id: '/_protected/_authenticated/timesheets/print/$year/$month'
      path: '/print/$year/$month'
      fullPath: '/timesheets/print/$year/$month'
      preLoaderRoute: typeof ProtectedAuthenticatedTimesheetsPrintYearMonthRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimesheetsRoute
    }
    '/_protected/_authenticated/time-entry/week/$year/$week': {
      id: '/_protected/_authenticated/time-entry/week/$year/$week'
      path: '/week/$year/$week'
      fullPath: '/time-entry/week/$year/$week'
      preLoaderRoute: typeof ProtectedAuthenticatedTimeEntryWeekYearWeekRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimeEntryRoute
    }
    '/_protected/_authenticated/time-entry/month/$year/$month': {
      id: '/_protected/_authenticated/time-entry/month/$year/$month'
      path: '/month/$year/$month'
      fullPath: '/time-entry/month/$year/$month'
      preLoaderRoute: typeof ProtectedAuthenticatedTimeEntryMonthYearMonthRouteImport
      parentRoute: typeof ProtectedAuthenticatedTimeEntryRoute
    }
  }
}

interface ProtectedAuthenticatedAdminUsersRouteChildren {
  ProtectedAuthenticatedAdminUsersIdRoute: typeof ProtectedAuthenticatedAdminUsersIdRoute
  ProtectedAuthenticatedAdminUsersNewRoute: typeof ProtectedAuthenticatedAdminUsersNewRoute
  ProtectedAuthenticatedAdminUsersIndexRoute: typeof ProtectedAuthenticatedAdminUsersIndexRoute
}

const ProtectedAuthenticatedAdminUsersRouteChildren: ProtectedAuthenticatedAdminUsersRouteChildren =
  {
    ProtectedAuthenticatedAdminUsersIdRoute:
      ProtectedAuthenticatedAdminUsersIdRoute,
    ProtectedAuthenticatedAdminUsersNewRoute:
      ProtectedAuthenticatedAdminUsersNewRoute,
    ProtectedAuthenticatedAdminUsersIndexRoute:
      ProtectedAuthenticatedAdminUsersIndexRoute,
  }

const ProtectedAuthenticatedAdminUsersRouteWithChildren =
  ProtectedAuthenticatedAdminUsersRoute._addFileChildren(
    ProtectedAuthenticatedAdminUsersRouteChildren,
  )

interface ProtectedAuthenticatedAdminRouteChildren {
  ProtectedAuthenticatedAdminUsersRoute: typeof ProtectedAuthenticatedAdminUsersRouteWithChildren
}

const ProtectedAuthenticatedAdminRouteChildren: ProtectedAuthenticatedAdminRouteChildren =
  {
    ProtectedAuthenticatedAdminUsersRoute:
      ProtectedAuthenticatedAdminUsersRouteWithChildren,
  }

const ProtectedAuthenticatedAdminRouteWithChildren =
  ProtectedAuthenticatedAdminRoute._addFileChildren(
    ProtectedAuthenticatedAdminRouteChildren,
  )

interface ProtectedAuthenticatedContractsRouteChildren {
  ProtectedAuthenticatedContractsContractIdRoute: typeof ProtectedAuthenticatedContractsContractIdRoute
  ProtectedAuthenticatedContractsNewRoute: typeof ProtectedAuthenticatedContractsNewRoute
  ProtectedAuthenticatedContractsIndexRoute: typeof ProtectedAuthenticatedContractsIndexRoute
}

const ProtectedAuthenticatedContractsRouteChildren: ProtectedAuthenticatedContractsRouteChildren =
  {
    ProtectedAuthenticatedContractsContractIdRoute:
      ProtectedAuthenticatedContractsContractIdRoute,
    ProtectedAuthenticatedContractsNewRoute:
      ProtectedAuthenticatedContractsNewRoute,
    ProtectedAuthenticatedContractsIndexRoute:
      ProtectedAuthenticatedContractsIndexRoute,
  }

const ProtectedAuthenticatedContractsRouteWithChildren =
  ProtectedAuthenticatedContractsRoute._addFileChildren(
    ProtectedAuthenticatedContractsRouteChildren,
  )

interface ProtectedAuthenticatedCustomersRouteChildren {
  ProtectedAuthenticatedCustomersIdRoute: typeof ProtectedAuthenticatedCustomersIdRoute
  ProtectedAuthenticatedCustomersNewRoute: typeof ProtectedAuthenticatedCustomersNewRoute
  ProtectedAuthenticatedCustomersIndexRoute: typeof ProtectedAuthenticatedCustomersIndexRoute
}

const ProtectedAuthenticatedCustomersRouteChildren: ProtectedAuthenticatedCustomersRouteChildren =
  {
    ProtectedAuthenticatedCustomersIdRoute:
      ProtectedAuthenticatedCustomersIdRoute,
    ProtectedAuthenticatedCustomersNewRoute:
      ProtectedAuthenticatedCustomersNewRoute,
    ProtectedAuthenticatedCustomersIndexRoute:
      ProtectedAuthenticatedCustomersIndexRoute,
  }

const ProtectedAuthenticatedCustomersRouteWithChildren =
  ProtectedAuthenticatedCustomersRoute._addFileChildren(
    ProtectedAuthenticatedCustomersRouteChildren,
  )

interface ProtectedAuthenticatedTimeEntryRouteChildren {
  ProtectedAuthenticatedTimeEntryIndexRoute: typeof ProtectedAuthenticatedTimeEntryIndexRoute
  ProtectedAuthenticatedTimeEntryMonthIndexRoute: typeof ProtectedAuthenticatedTimeEntryMonthIndexRoute
  ProtectedAuthenticatedTimeEntryWeekIndexRoute: typeof ProtectedAuthenticatedTimeEntryWeekIndexRoute
  ProtectedAuthenticatedTimeEntryMonthYearMonthRoute: typeof ProtectedAuthenticatedTimeEntryMonthYearMonthRoute
  ProtectedAuthenticatedTimeEntryWeekYearWeekRoute: typeof ProtectedAuthenticatedTimeEntryWeekYearWeekRoute
}

const ProtectedAuthenticatedTimeEntryRouteChildren: ProtectedAuthenticatedTimeEntryRouteChildren =
  {
    ProtectedAuthenticatedTimeEntryIndexRoute:
      ProtectedAuthenticatedTimeEntryIndexRoute,
    ProtectedAuthenticatedTimeEntryMonthIndexRoute:
      ProtectedAuthenticatedTimeEntryMonthIndexRoute,
    ProtectedAuthenticatedTimeEntryWeekIndexRoute:
      ProtectedAuthenticatedTimeEntryWeekIndexRoute,
    ProtectedAuthenticatedTimeEntryMonthYearMonthRoute:
      ProtectedAuthenticatedTimeEntryMonthYearMonthRoute,
    ProtectedAuthenticatedTimeEntryWeekYearWeekRoute:
      ProtectedAuthenticatedTimeEntryWeekYearWeekRoute,
  }

const ProtectedAuthenticatedTimeEntryRouteWithChildren =
  ProtectedAuthenticatedTimeEntryRoute._addFileChildren(
    ProtectedAuthenticatedTimeEntryRouteChildren,
  )

interface ProtectedAuthenticatedTimesheetsRouteChildren {
  ProtectedAuthenticatedTimesheetsIndexRoute: typeof ProtectedAuthenticatedTimesheetsIndexRoute
  ProtectedAuthenticatedTimesheetsPrintYearMonthRoute: typeof ProtectedAuthenticatedTimesheetsPrintYearMonthRoute
}

const ProtectedAuthenticatedTimesheetsRouteChildren: ProtectedAuthenticatedTimesheetsRouteChildren =
  {
    ProtectedAuthenticatedTimesheetsIndexRoute:
      ProtectedAuthenticatedTimesheetsIndexRoute,
    ProtectedAuthenticatedTimesheetsPrintYearMonthRoute:
      ProtectedAuthenticatedTimesheetsPrintYearMonthRoute,
  }

const ProtectedAuthenticatedTimesheetsRouteWithChildren =
  ProtectedAuthenticatedTimesheetsRoute._addFileChildren(
    ProtectedAuthenticatedTimesheetsRouteChildren,
  )

interface ProtectedAuthenticatedRouteChildren {
  ProtectedAuthenticatedAdminRoute: typeof ProtectedAuthenticatedAdminRouteWithChildren
  ProtectedAuthenticatedContractsRoute: typeof ProtectedAuthenticatedContractsRouteWithChildren
  ProtectedAuthenticatedCustomersRoute: typeof ProtectedAuthenticatedCustomersRouteWithChildren
  ProtectedAuthenticatedTimeEntryRoute: typeof ProtectedAuthenticatedTimeEntryRouteWithChildren
  ProtectedAuthenticatedTimesheetsRoute: typeof ProtectedAuthenticatedTimesheetsRouteWithChildren
  ProtectedAuthenticatedLeavesYearRoute: typeof ProtectedAuthenticatedLeavesYearRoute
  ProtectedAuthenticatedLeavesIndexRoute: typeof ProtectedAuthenticatedLeavesIndexRoute
}

const ProtectedAuthenticatedRouteChildren: ProtectedAuthenticatedRouteChildren =
  {
    ProtectedAuthenticatedAdminRoute:
      ProtectedAuthenticatedAdminRouteWithChildren,
    ProtectedAuthenticatedContractsRoute:
      ProtectedAuthenticatedContractsRouteWithChildren,
    ProtectedAuthenticatedCustomersRoute:
      ProtectedAuthenticatedCustomersRouteWithChildren,
    ProtectedAuthenticatedTimeEntryRoute:
      ProtectedAuthenticatedTimeEntryRouteWithChildren,
    ProtectedAuthenticatedTimesheetsRoute:
      ProtectedAuthenticatedTimesheetsRouteWithChildren,
    ProtectedAuthenticatedLeavesYearRoute:
      ProtectedAuthenticatedLeavesYearRoute,
    ProtectedAuthenticatedLeavesIndexRoute:
      ProtectedAuthenticatedLeavesIndexRoute,
  }

const ProtectedAuthenticatedRouteWithChildren =
  ProtectedAuthenticatedRoute._addFileChildren(
    ProtectedAuthenticatedRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAuthenticatedRoute: typeof ProtectedAuthenticatedRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAuthenticatedRoute: ProtectedAuthenticatedRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  NoAccessRoute: NoAccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
