/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AnonymousTypeOfstringAndstring'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          role?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateUserCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/paged': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          search?: string;
          sortBy?: string;
          sortDir?: string;
          pageSize?: number;
          cursor?: string;
          deletedOnly?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['KeysetPageOfUserDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetUserById'];
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CustomerDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateCustomerCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/paged': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          search?: string;
          sortBy?: string;
          sortDir?: string;
          pageSize?: number;
          cursor?: string;
          deletedOnly?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['KeysetPageOfCustomerDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/customers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetCustomerById'];
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateCustomerCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/contracts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          search?: string;
          sortBy?: string;
          sortDir?: string;
          pageSize?: number;
          cursor?: string;
          deletedOnly?: boolean;
          activeOnDate?: string;
          customerId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['KeysetPageOfContractSummaryDto'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateContractCommand'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ContractDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/contracts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetContractById'];
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateContractCommand'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/leaves': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          year?: number;
        };
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserLeaveDto'][];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserLeavesBody'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UserLeaveDto'][];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timesheet-weeks/{userId}/{year}/{week}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          year: number;
          week: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timesheet-weeks/{userId}/{year}/{week}/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          year: number;
          week: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApplyBookingsRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timesheet-weeks/{userId}/{year}/{week}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          year: number;
          week: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timesheet-weeks/{userId}/{year}/{week}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          year: number;
          week: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timesheet-weeks/{userId}/{year}/{week}/reopen': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          year: number;
          week: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/timesheet-selectable-tasks/{userId}/{year}/{week}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          year: number;
          week: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddressDto: {
      street: null | string;
      zip: null | string;
      city: null | string;
      country: null | string;
    };
    AnonymousTypeOfstringAndstring: {
      name: null | string;
      version: null | string;
    };
    ApplyBookingsRequest: {
      bookings: components['schemas']['BookingInputDto'][];
    };
    BookingInputDto: {
      /** Format: uuid */
      contractTaskId: string;
      /** Format: date */
      date: string;
      /** Format: double */
      durationHours: number;
    };
    DayInfoDto: {
      /** Format: date */
      date: string;
      isBusinessDay: boolean;
    };
    SelectableContractTaskDto: {
      /** Format: uuid */
      contractTaskId: string;
      taskName: string;
      /** Format: uuid */
      contractId: string;
      contractSubject: string;
      /** Format: uuid */
      customerId: string;
    };
    TimeEntryDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      contractTaskId: string;
      taskName: string;
      /** Format: uuid */
      contractId: string;
      contractSubject: string;
      /** Format: uuid */
      customerId: string;
      customerName: string;
      /** Format: date */
      date: string;
      /** Format: double */
      durationHours: number;
    };
    TimesheetWeekDto: {
      /** Format: uuid */
      id: null | string;
      /** Format: uuid */
      userId: string;
      /** Format: int32 */
      isoYear: number;
      /** Format: int32 */
      isoWeek: number;
      status: string;
      days: components['schemas']['DayInfoDto'][];
      timeEntries: components['schemas']['TimeEntryDto'][];
    };
    ContactPersonDto: {
      name: null | string;
      email: string;
    };
    ContractDto: {
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      number: number;
      subject: string;
      /** Format: uuid */
      customerId: string;
      /** Format: uuid */
      clientManagerId: null | string;
      /** Format: date */
      start: string;
      /** Format: date */
      end: null | string;
      tasks: components['schemas']['ContractTaskDto'][];
      consultantIds: string[];
    };
    ContractSummaryDto: {
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      number: number;
      subject: string;
      /** Format: uuid */
      customerId: string;
      /** Format: date */
      start: string;
      /** Format: date */
      end: null | string;
      /** Format: int32 */
      activeTaskCount: number;
      /** Format: int32 */
      consultantCount: number;
    };
    ContractTaskDto: {
      /** Format: uuid */
      id: string;
      name: string;
      /** Format: double */
      rate: number;
      /** Format: date-time */
      deletedAt: null | string;
    };
    CreateContractCommand: {
      subject: string;
      /** Format: uuid */
      customerId: string;
      /** Format: date */
      start: string;
      /** Format: date */
      end: null | string;
    };
    CreateCustomerCommand: {
      name: string;
      contactPerson: components['schemas']['ContactPersonDto'];
      address: null | components['schemas']['AddressDto'];
      /** Format: uuid */
      clientManagerId: null | string;
    };
    CreateUserCommand: {
      firstName: string;
      lastName: string;
      email: string;
      roles: components['schemas']['UserRole'][];
    };
    CustomerDto: {
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      number: number;
      name: string;
      address: components['schemas']['AddressDto'];
      contactPerson: components['schemas']['ContactPersonDto'];
      /** Format: uuid */
      clientManagerId: null | string;
    };
    KeysetPageOfContractSummaryDto: {
      items: components['schemas']['ContractSummaryDto'][];
      nextCursor: null | string;
      /** Format: int32 */
      total: number;
    };
    KeysetPageOfCustomerDto: {
      items: components['schemas']['CustomerDto'][];
      nextCursor: null | string;
      /** Format: int32 */
      total: number;
    };
    KeysetPageOfUserDto: {
      items: components['schemas']['UserDto'][];
      nextCursor: null | string;
      /** Format: int32 */
      total: number;
    };
    /** @enum {unknown} */
    LeaveAllowed: 'NotAllowed' | 'Limited' | 'Unlimited';
    UpdateContractCommand: {
      /** Format: uuid */
      id: string;
      subject: string;
      /** Format: uuid */
      clientManagerId: null | string;
      /** Format: date */
      start: string;
      /** Format: date */
      end: null | string;
      consultantIds: string[];
      tasks?: null | components['schemas']['UpdateContractTaskDto'][];
    };
    UpdateContractTaskDto: {
      /** Format: uuid */
      id: null | string;
      name: string;
      /** Format: double */
      rate: number;
    };
    UpdateCustomerCommand: {
      /** Format: uuid */
      id: string;
      name: string;
      contactPerson: components['schemas']['ContactPersonDto'];
      address: null | components['schemas']['AddressDto'];
      /** Format: uuid */
      clientManagerId: null | string;
    };
    UpdateUserCommand: {
      /** Format: uuid */
      id: string;
      firstName: string;
      lastName: string;
      roles: components['schemas']['UserRole'][];
    };
    UpdateUserLeavesBody: {
      /** Format: int32 */
      year: number;
      items: components['schemas']['UpdateUserLeavesItem'][];
    };
    UpdateUserLeavesItem: {
      /** Format: uuid */
      id: string;
      /** Format: double */
      totalDays: null | number;
    };
    UserDto: {
      /** Format: uuid */
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      roles: components['schemas']['UserRole'][];
    };
    UserLeaveDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      leaveTypeId: string;
      leaveTypeName: string;
      defaultAllowed: components['schemas']['LeaveAllowed'];
      /** Format: int32 */
      year: number;
      /** Format: double */
      totalDays: null | number;
      /** Format: double */
      takenDays: null | number;
      /** Format: double */
      balanceDays: null | number;
    };
    /** @enum {unknown} */
    UserRole: 'User' | 'Admin' | 'ClientManager';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetCustomerById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetContractById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
